### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by lorddaedra** [cloudflare-api/python-cloudflare-v4#13]
```
➜  ipmonitor python3 -m pip install -U git+https://github.com/cloudflare-api/python-cloudflare-v4
...
➜  ipmonitor python3
Python 3.5.0 (default, Sep 19 2015, 20:11:34)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.57.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import CloudFlare
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lorddaedra/.pyenv/versions/3.5.0/lib/python3.5/site-packages/CloudFlare/__init__.py", line 22
    self.BASE_URL = base_url
                           ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by mahtin** [comment]
This has been fixed within [python-cloudflare](https://github.com/cloudflare/python-cloudflare) under [Cloudflare](https://github.com/cloudflare). It installs and runs under Python2 & Python3.

Enjoy
