### ISSUE TITLE
ImportError: No module named 'cloudflare'

### ISSUE THREAD

**Issue by Routhinator** [cloudflare-api/python-cloudflare-v4#15]
I cannot open issues on the new repository for some silly reason, so opening one here.

This module fails to install in both Python 2 and Python 3 due to what seems to be a circular import issue.

```
Collecting cloudflare
  Using cached cloudflare-1.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pycharm-packaging0.tmp/cloudflare/setup.py", line 5, in <module>
        from CloudFlare import __version__
      File "/tmp/pycharm-packaging0.tmp/cloudflare/CloudFlare/__init__.py", line 3, in <module>
        from cloudflare import CloudFlare
    ImportError: No module named 'cloudflare'
    
    ----------------------------------------
```

**Comment by Routhinator** [comment]
Verified that this occurs with the Github AND pip methods of installation:

 ./setup.py build
Traceback (most recent call last):
  File "./setup.py", line 5, in <module>
    from CloudFlare import __version__
  File "/home/routh/PycharmProjects/cloudflare-deploy/cloudflare/CloudFlare/__init__.py", line 3, in <module>
    from cloudflare import CloudFlare
ImportError: No module named 'cloudflare'

**Comment by Routhinator** [comment]
Turns out this was Python3 causing the issue. The module is not yet Python3 ready it would seem.

Fixed by switching to Python2.
